//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIM_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public long DireccionID { get; set; }
        public string Calle { get; set; }
        public decimal Numero { get; set; }
        public Nullable<decimal> Piso { get; set; }
        public string Departamento { get; set; }
        public string Localidad { get; set; }
        public string Provincia { get; set; }
        public Nullable<long> CampaniaID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public Nullable<long> MascotaID { get; set; }
    
        public virtual Campania Campania { get; set; }
        public virtual Mascota Mascota { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
