//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIM_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicamentosMascotas
    {
        public long MascotaID { get; set; }
        public string MedicamentID { get; set; }
        public decimal Dosis { get; set; }
        public System.TimeSpan Frecuencia { get; set; }
        public Nullable<int> RenglonVisita { get; set; }
    
        public virtual Mascota Mascota { get; set; }
        public virtual Medicamento Medicamento { get; set; }
        public virtual VeterinarioMascota VeterinarioMascota { get; set; }
    }
}
