//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIM_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Campania = new HashSet<Campania>();
            this.Direccion = new HashSet<Direccion>();
            this.Mascota = new HashSet<Mascota>();
        }
    
        public int UsuarioID { get; set; }
        public string Apellido { get; set; }
        public Nullable<System.DateTime> FechaConfirmacionAlta { get; set; }
        public string Nombre { get; set; }
        public string TipoUsuario { get; set; }
        public string Telefono { get; set; }
        public string ImagenDNI { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public short TipoDocumento { get; set; }
        public decimal NumeroDocumento { get; set; }
        public string CodigoVerificacion { get; set; }
        public string Imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campania> Campania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direccion> Direccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mascota> Mascota { get; set; }
        public virtual Veterinario Veterinario { get; set; }
    }
}
