//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIM_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacunacion
    {
        public long MascotaID { get; set; }
        public int RenglonVacuna { get; set; }
        public Nullable<System.DateTime> FechaRevacunacion { get; set; }
        public System.DateTime FechaAplicacion { get; set; }
        public string CodigoSENASA { get; set; }
        public string Lote { get; set; }
        public string Serie { get; set; }
        public string Dosis { get; set; }
        public int VacunaID { get; set; }
        public Nullable<int> RenglonVisita { get; set; }
    
        public virtual Mascota Mascota { get; set; }
        public virtual TipoVacuna TipoVacuna { get; set; }
        public virtual VeterinarioMascota VeterinarioMascota { get; set; }
    }
}
