//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIM_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeterinarioMascota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VeterinarioMascota()
        {
            this.Fallecimiento = new HashSet<Fallecimiento>();
            this.MedicamentosMascotas = new HashSet<MedicamentosMascotas>();
            this.Vacunacion = new HashSet<Vacunacion>();
        }
    
        public long MascotaID { get; set; }
        public int RenglonVisita { get; set; }
        public System.DateTime FechaConsulta { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Peso { get; set; }
        public byte ReportoENO { get; set; }
        public string TipoID { get; set; }
        public int VeterinarioID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fallecimiento> Fallecimiento { get; set; }
        public virtual Mascota Mascota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicamentosMascotas> MedicamentosMascotas { get; set; }
        public virtual TipoVisita TipoVisita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacunacion> Vacunacion { get; set; }
        public virtual Veterinario Veterinario { get; set; }
    }
}
