//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIM_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeterinarioMascota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VeterinarioMascota()
        {
            this.Fallecimientoes = new HashSet<Fallecimiento>();
            this.MedicamentosMascotas = new HashSet<MedicamentosMascota>();
            this.Vacunacions = new HashSet<Vacunacion>();
        }
    
        public long MascotaID { get; set; }
        public int RenglonVisita { get; set; }
        public System.DateTime FechaConsulta { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Peso { get; set; }
        public byte ReportoENO { get; set; }
        public string TipoID { get; set; }
        public int VeterinarioID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fallecimiento> Fallecimientoes { get; set; }
        public virtual Mascota Mascota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicamentosMascota> MedicamentosMascotas { get; set; }
        public virtual TipoVisita TipoVisita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacunacion> Vacunacions { get; set; }
        public virtual Veterinario Veterinario { get; set; }
    }
}
